algoritmo "volume paralelepipedo"
// Função:calcular o volume do paralelepipedo
// Autor :Gabriel martins
// Data : 13/04/2026
// Seção de Declarações 
var
n1, n2, n3: real
valorFinal:real
inicio
// Seção de Comando
escreva("digite a base")
leia (n1)
escreva("digite a altura")
 leia (n2)
escreva ("digite a largura")
 leia (n3)
//calculo

valorFinal<- n1*n2*n3
escreval("o valor do volume é:",valorFinal)
fimalgoritmo
