algoritmo "Soma de 3 numeros"
// Função :Somar 3 numeros
// Autor :Gabriel martins
// Data : 13/04/2026
// Seção de Declarações 
var
n1, n2, n3: real
valorFinal:real
inicio
// Seção de Comando
escreva("digite o primeiro numero")
leia (n1)
escreva("digite o segundo numero")
 leia (n2)
escreva ("digite o terceiro numero")
 leia (n3)
//calculo

valorFinal<- n1+n2+n3
escreval("o valor da soma é:",valorFinal)
fimalgoritmo
